version: '2.4'
services:

  psql:
    container_name: psql
    image: postgres:11-alpine
    environment:
      # Super-User: by default POSTGRES_USER="postgres"
      - "POSTGRES_DB=${POSTGRES_DB}"
#      - "POSTGRES_USER=${POSTGRES_USER}"
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
    ports:
      - "${POSTGRES_PORT}:5432"
    #restart: always
    volumes:
      - ./psql/data:/var/lib/postgresql/data
      - ./src/main/resources/init.sql:/docker-entrypoint-initdb.d/init.sql
